# -*- coding: utf-8 -*-
"""VuVoBinhAn.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KinrOdqOuRf2J0aUz8ctFyDxknhJSzyj
"""

# bai 1
print("bai tap python")
a = float(input("nhap a: "))
b = float(input("nhap b: "))
print ("a + b = ", a + b)
print ("a - b = ", a - b)
print ("a * b = ", a * b)
print("a / b = ", a/b)

# bai 2
a = "hello world"
ketqua = a[2:5]
print(ketqua)

# bai 3
s = "   Hello World  "


s_trimmed = s.strip()


s_upper = s_trimmed.upper()


s_lower = s_trimmed.lower()


# Luu y: replace() co phan biet hoa thuong
s_replaced = s_trimmed.replace("H", "J")



print(f"Xoa khoang trang: '{s_trimmed}'")
print(f"Chu hoa: '{s_upper}'")
print(f"Chu thuong: '{s_lower}'")
print(f"Thay H bang J: '{s_replaced}'")

#bai 4
a = float(input("nhap a: "))
b = float(input("nhap b: "))
if a > b:
  print("hello world")
else:
    print("sai de bai")

# bai 5
a = float(input("nhap a: "))
b = float(input("nhap b:"))
if a == b:
  print("yes")
else:
  print("no")

# bai 6
a = float(input("nhap a: "))
b = float(input("nhap b: "))
if a==b:
  print("1")
elif a>b:
  print("2")
else:
  print("nhap laij")

# bai 7
a = float(input("nhap a: "))
b = float(input("nhap b: "))
d = float(input("nhap d: "))
if a ==b and b==d:
  print("Hello world")
else:
  print("nhap lai")

# bai 8
a = float(input("nhap a: "))
b = float(input("nhap b: "))
c = float(input("nhap c: "))
d = float(input("nhap d: "))
if a ==b and c==d:
  print("Hello world")
else:
  print("nhap lai")

# bai 9
a = float(input("nhap a: "))
b = float(input("nhap b: "))
print('yes') if a>b else print('no')

# bai 10
a = float(input("nhap a: "))
b = float(input("nhap b: "))
print("A") if a > b else print("=") if a == b else print("B")

#bai 11
n = int(input("nhap so luong phan tu cua mang: "))
a = []

for i in range(n):
    val = int(input(f"nhap gia tri cho phan tu thu {i}: "))
    a.append(val)

# Đưa các dòng này ra sát lề trái để chạy SAU KHI vòng lặp kết thúc
b = [x for x in a if x % 2 == 0]
print("Mang a vua nhap la:", a)
print("Cac so chan trong mang a la:", b)

#bai12
tong = 0
for i in range (1000):
  if i % 3 == 0 or i % 5 == 0:
    tong = tong + i
    print("Tổng các số từ 0 đến 999 là bội của 3 hoặc 5 là:", tong)

#bai13
def tron_mang(a, b):
    mang_moi = []
    i = 0
    # Lay do dai nho nhat cua 2 mang de cong cac phan tu tuong ung
    min_len = min(len(a), len(b))

    # Buoc 1: Cong cac phan tu tuong ung
    while i < min_len:
        mang_moi.append(a[i] + b[i])
        i += 1

    # Buoc 2: Xu ly phan con du cua mang dai hon
    # Neu mang a dai hon
    if len(a) > len(b):
        phan_du = a[i:] # Lay cac phan tu con lai cua a
        tong_phan_du = sum(phan_du)
        mang_moi.append(tong_phan_du)

    # Neu mang b dai hon
    elif len(b) > len(a):
        phan_du = b[i:] # Lay cac phan tu con lai cua b
        tong_phan_du = sum(phan_du)
        mang_moi.append(tong_phan_du)

    return mang_moi

# Chay thu voi vi du cua ban
a = [3, 9, 1, 4]
b = [2, 7, 4, 3, 2, 8]

ket_qua = tron_mang(a, b)
print("Mang a:", a)
print("Mang b:", b)
print("Mang ket qua:", ket_qua)

#bai14
import random

# --- CÁC HÀM XỬ LÝ (THEO ĐỀ BÀI) ---

def tao_ma_tran(m, n):
    """a. Tạo mảng a chứa các số nguyên ngẫu nhiên từ 1-100"""
    return [[random.randint(1, 100) for _ in range(n)] for _ in range(m)]

def xuat_dong_k(a, k):
    """b. Xuất các phần tử thuộc dòng k"""
    if 0 <= k < len(a):
        print(f"Dòng {k}: {a[k]}")
    else:
        print(f"Lỗi: Dòng {k} không tồn tại!")

def xuat_cot_k(a, k):
    """c. Xuất các phần tử thuộc cột k"""
    if 0 <= k < len(a[0]):
        cot = [a[i][k] for i in range(len(a))]
        print(f"Cột {k}: {cot}")
    else:
        print(f"Lỗi: Cột {k} không tồn tại!")

def dong_tong_max(a):
    """d. Tìm dòng có tổng lớn nhất"""
    max_val = -1
    index = -1
    for i, dong in enumerate(a):
        tong = sum(dong)
        if tong > max_val:
            max_val = tong
            index = i
    print(f"Dòng {index} có tổng lớn nhất là: {max_val}")

def cot_tich_min(a):
    """e. Tìm cột có tích nhỏ nhất"""
    m, n = len(a), len(a[0])
    min_tich = float('inf')
    index_cot = -1
    for j in range(n):
        tich = 1
        for i in range(m):
            tich *= a[i][j]
        if tich < min_tich:
            min_tich = tich
            index_cot = j
    print(f"Cột {index_cot} có tích nhỏ nhất là: {min_tich}")

def xuat_dong_chan_cot_le(a):
    """f. Xuất các phần tử thuộc dòng chẵn và cột lẻ"""
    print("Các phần tử (dòng chẵn, cột lẻ):")
    for i in range(0, len(a), 2):
        for j in range(1, len(a[0]), 2):
            print(f"a[{i}][{j}]={a[i][j]}", end="  ")
    print()

def tbc_chan_dong_le(a):
    """g. TBC các phần tử chẵn thuộc dòng lẻ"""
    ds = [x for i in range(1, len(a), 2) for x in a[i] if x % 2 == 0]
    kq = sum(ds)/len(ds) if ds else 0
    print(f"TBC phần tử chẵn ở dòng lẻ: {kq:.2f}")

def tinh_bien_va_noi_tai(a):
    """h. TBC biên và Trung bình tích không thuộc biên"""
    m, n = len(a), len(a[0])
    bien = []
    noi_tai = []
    for i in range(m):
        for j in range(n):
            if i == 0 or i == m-1 or j == 0 or j == n-1:
                bien.append(a[i][j])
            else:
                noi_tai.append(a[i][j])

    tbc_bien = sum(bien)/len(bien) if bien else 0

    tich = 1
    for x in noi_tai: tich *= x
    tb_tich = tich / len(noi_tai) if noi_tai else 0

    print(f"TBC phần tử biên: {tbc_bien:.2f}")
    print(f"Trung bình tích phần tử bên trong: {tb_tich:.2f}")

# --- CHƯƠNG TRÌNH CHÍNH ---

# 1. Nhập kích thước và tạo ma trận
m = int(input("Nhập số dòng m: "))
n = int(input("Nhập số cột n: "))
matrix = tao_ma_tran(m, n)

print("\n--- MA TRẬN NGẪU NHIÊN ---")
for row in matrix:
    print(row)

# 2. Gọi thử các hàm
print("\n--- KẾT QUẢ THỰC THI ---")
xuat_dong_k(matrix, 0)
xuat_cot_k(matrix, 0)
dong_tong_max(matrix)
cot_tich_min(matrix)
xuat_dong_chan_cot_le(matrix)
tbc_chan_dong_le(matrix)
tinh_bien_va_noi_tai(matrix)

#bai
import datetime

# a. Xây dựng cấu trúc SINHVIEN
class SinhVien:
    def __init__(self, ma_sv, ten, nam_sinh, diem_tb):
        self.ma_sv = ma_sv[:10]      # Tối đa 10 ký tự
        self.ten = ten[:20]          # Tối đa 20 ký tự
        self.nam_sinh = int(nam_sinh)
        self.diem_tb = float(diem_tb)

    def __str__(self):
        return f"MSV: {self.ma_sv} | Tên: {self.ten} | Năm sinh: {self.nam_sinh} | ĐTB: {self.diem_tb}"

# b. Hàm nhập danh sách n sinh viên
def nhap_danh_sach_sv(n):
    danh_sach = []
    for i in range(n):
        print(f"\nNhập thông tin sinh viên thứ {i+1}:")
        ma = input("Mã SV (10 ký tự): ")
        ten = input("Tên SV (tối đa 20 ký tự): ")
        nam = int(input("Năm sinh: "))
        diem = float(input("Điểm trung bình: "))
        sv = SinhVien(ma, ten, nam, diem)
        danh_sach.append(sv)
    return danh_sach

# c. Đếm sinh viên đủ điều kiện lên lớp (ĐTB >= 5)
def dem_sv_len_lop(ds):
    count = sum(1 for sv in ds if sv.diem_tb >= 5)
    print(f"\nSố sinh viên đủ điều kiện lên lớp: {count}")
    return count

# d. Xuất các sinh viên đủ 20 tuổi
def xuat_sv_20_tuoi(ds):
    nam_hien_tai = datetime.datetime.now().year
    print("\nDanh sách sinh viên đủ 20 tuổi:")
    found = False
    for sv in ds:
        if (nam_hien_tai - sv.nam_sinh) == 20:
            print(sv)
            found = True
    if not found: print("Không có sinh viên nào 20 tuổi.")

# e. Đếm sinh viên hệ Đại học (Mã chứa 'DH' ở vị trí 2, 3)
# Lưu ý: Vị trí 2,3 trong chuỗi (tính từ 0) là index 2 và 3
def dem_sv_he_dh(ds):
    count = 0
    for sv in ds:
        # Kiểm tra nếu chuỗi con từ index 2 đến 4 là "DH"
        if len(sv.ma_sv) >= 4 and sv.ma_sv[2:4].upper() == "DH":
            count += 1
    print(f"Số sinh viên hệ Đại học: {count}")

# f. Đếm sinh viên tên "Lan"
def dem_ten_lan(ds):
    # Lấy phần tên cuối cùng trong chuỗi họ tên
    count = 0
    for sv in ds:
        ten_tach_ra = sv.ten.split()[-1].lower()
        if ten_tach_ra == "lan":
            count += 1
    print(f"Số sinh viên tên Lan: {count}")

# g. Đếm sinh viên họ "Phan"
def dem_ho_phan(ds):
    count = 0
    for sv in ds:
        ho_tach_ra = sv.ten.split()[0].lower()
        if ho_tach_ra == "phan":
            count += 1
    print(f"Số sinh viên họ Phan: {count}")

# --- CHƯƠNG TRÌNH CHÍNH ---
def main():
    n = int(input("Nhập số lượng sinh viên n: "))
    ds_sinh_vien = nhap_danh_sach_sv(n)

    print("\n" + "="*30)
    print("KẾT QUẢ PHÂN TÍCH")
    print("="*30)

    dem_sv_len_lop(ds_sinh_vien)
    xuat_sv_20_tuoi(ds_sinh_vien)
    dem_sv_he_dh(ds_sinh_vien)
    dem_ten_lan(ds_sinh_vien)
    dem_ho_phan(ds_sinh_vien)

if __name__ == "__main__":
    main()